"use client"

import { useState } from "react"
import { useLocale, useTranslations } from "next-intl"
import { Check, Coffee, MessageSquareQuote, ShoppingBag, Utensils } from "lucide-react"
import { cn } from "@/lib/utils"
import { formatOrderId } from "@/lib/format"
import { SegmentedControl } from "@/components/motion/segmented-control"
import type { KdsStatus, KdsOrder } from "@/hooks/useKitchenOrders"

const COLUMNS: { status: KdsStatus; key: "columnNew" | "columnPreparing" | "columnReady"; dot: string }[] = [
  { status: "paid", key: "columnNew", dot: "bg-primary" }, { status: "preparing", key: "columnPreparing", dot: "bg-amber-600" }, { status: "ready", key: "columnReady", dot: "bg-success" },
]
export function formatElapsed(createdAt: number, now: number) { const seconds = Math.max(0, Math.floor((now - createdAt) / 1000)); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}` }
export type UrgencyLevel = "normal" | "warning" | "critical"
export function urgencyLevelFor(createdAt: number, now: number): UrgencyLevel { const minutes = (now - createdAt) / 60000; return minutes >= 15 ? "critical" : minutes >= 10 ? "warning" : "normal" }
export function KitchenBoard({ orders, now, onAdvanceItem, isItemPending }: { orders: KdsOrder[]; now: number; onAdvanceItem: (orderId: string, itemId: string) => void; isItemPending: (orderId: string, itemId: string) => boolean }) {
  const t = useTranslations("KitchenDisplay"); const locale = useLocale(); const [mobileColumn, setMobileColumn] = useState<KdsStatus>("paid")
  return <div className="flex h-full min-h-0 flex-col overflow-hidden"><SegmentedControl variant="tabs" layoutId="kds-mobile-columns" className="mb-3 md:hidden" value={mobileColumn} onChange={setMobileColumn} options={COLUMNS.map(({ status, key }) => ({ value: status, label: t(key) }))} /><div className="grid min-h-0 flex-1 grid-cols-1 overflow-hidden md:grid-cols-3">{COLUMNS.map((column, index) => { const tickets = orders.filter((order) => order.status === column.status); return <section key={column.status} className={cn("min-h-0 flex-col overflow-hidden border-border md:flex md:border-r-2", index === 2 && "md:border-r-0", mobileColumn === column.status ? "flex" : "hidden md:flex")}><header className="flex shrink-0 items-center gap-2.5 border-b-[2.5px] border-ink bg-chip px-4 py-3"><span className={cn("size-2.5 rounded-sm", column.dot)} /><h2 className="flex-1 text-[13px] font-extrabold">{t(column.key)}</h2><span className="nb-border-sm rounded-full bg-card px-2 py-0.5 text-xs font-extrabold">{tickets.length}</span></header><div className="kds-col flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto p-3.5">{tickets.length === 0 && <div className="flex flex-col items-center gap-2 rounded-xl border-[2.5px] border-dashed border-border px-4 py-7 text-center text-xs font-bold text-muted-foreground"><Coffee className="size-6" />{t("empty")}</div>}{tickets.map((order) => <Ticket key={order.id} order={order} now={now} locale={locale} onAdvanceItem={onAdvanceItem} isItemPending={isItemPending} />)}</div></section> })}</div></div>
}
function Ticket({ order, now, locale, onAdvanceItem, isItemPending }: { order: KdsOrder; now: number; locale: string; onAdvanceItem: (orderId: string, itemId: string) => void; isItemPending: (orderId: string, itemId: string) => boolean }) {
  const t = useTranslations("KitchenDisplay"); const next = order.items.find((item) => item.status !== "served"); const done = order.items.filter((item) => item.status === "served").length; const late = now - order.createdAt >= 600000
  return <article className="nb-border nb-shadow-sm flex flex-col gap-3 rounded-xl bg-card p-3"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><p className="text-[17px] leading-none font-extrabold">#{formatOrderId(order.id)}</p><div className="mt-1.5 flex items-center gap-1.5"><span className={cn("nb-border-sm inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-extrabold", order.orderType === "pickup" ? "bg-chip" : "bg-accent text-accent-foreground")}>{order.orderType === "pickup" ? <ShoppingBag className="size-3" /> : <Utensils className="size-3" />}{order.orderType === "pickup" ? t("pickup") : t("table", { table: order.table ?? "" })}</span><span className="text-[11px] font-semibold text-muted-foreground">{new Date(order.createdAt).toLocaleTimeString(locale === "vi" ? "vi-VN" : "en-US", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Ho_Chi_Minh" })}</span></div></div><div className="text-right"><p className={cn("text-xl leading-none font-extrabold", late ? "text-destructive" : "text-card-foreground")}>{formatElapsed(order.createdAt, now)}</p><p className="mt-1 text-[10px] font-bold text-muted-foreground">{done}/{order.items.length} {t("itemsLabel")}</p></div></div><div className="flex flex-col gap-2">{order.items.map((item) => { const complete = item.status === "served"; return <button key={item.id} type="button" onClick={() => onAdvanceItem(order.id, item.id)} disabled={complete || isItemPending(order.id, item.id)} className="flex items-start gap-2 text-left disabled:pointer-events-none"><span className={cn("nb-border-sm mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-[5px]", complete ? "bg-success text-white" : "bg-card")}>{complete && <Check className="size-3" />}</span><span className={cn("min-w-0 flex-1 text-sm font-extrabold leading-tight", complete && "text-muted-foreground line-through")}>{item.quantity}× {locale === "vi" ? item.nameVi : item.nameEn}{item.note && <span className="mt-1 block text-[11px] font-semibold text-muted-foreground no-underline">{item.note}</span>}</span></button> })}</div>{order.items.some((item) => item.note) && <div className="nb-border-sm flex items-start gap-2 rounded-md bg-warn/15 px-2.5 py-2 text-[11px] font-bold"><MessageSquareQuote className="size-4 shrink-0 text-warn" />{order.items.find((item) => item.note)?.note}</div>}{next && <button type="button" onClick={() => onAdvanceItem(order.id, next.id)} disabled={isItemPending(order.id, next.id)} className={cn("nb-border nb-shadow nb-press h-10 rounded-lg text-xs font-extrabold uppercase tracking-wide text-white disabled:opacity-40", next.status === "ready" ? "bg-success" : "bg-primary")}>{next.status === "ready" ? t("markServed") : t("markReady")}</button>}</article>
}
